### ISSUE TITLE
Keeps redirecting to root path

### ISSUE THREAD

**Issue by peter-wd-1** [authorizerdev/authorizer#159]
**Version:** 0.21

**Describe the bug**

If I goto dashboard URL, whatever I've set the authorizer url, It automatically redirect to root URL 
e.g. www.xyz.com/authadmin -> redireact to www.xyz.com 

**Steps To Reproduce**

1. setup EC2, nginx, domain. 
Nginx:
```
location /authadmin/ {
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
        proxy_pass         "http://127.0.0.1:8081";
    }
```
2. deploy with docker-compose in the repo
3. access dashboard with your domain www.abc.com/authadmin

it will redirect you to www.abc.com/dashboard

**Expected behavior**

should use base url www.abc.com/authadmin/ as given and access dashboard to 
www.abc.com/authadmin/dashboard

**Desktop (please complete the following information):**

- OS: AWS linux 2
- Browser: chrome
- Version: Version 100.0.4896.127 (Official Build) (x86_64)

my .env file
```
DATABASE_URL=mongodb://root:admin123!@<prod-ipaddress>:27017
DATABASE_TYPE=mongodb
AUTHORIZER_URL=https://<prod-domain>/authadmin/
PORT=8080
ENV=production
```
docker compose
```
version: '3.9'
services:
  authorizer:
    build: .
    ports:
      - 8081:8080
    env_file:
      - /home/ec2-user/authorizer/.env
```

and it just works fine with localhost. 

I love your work btw Thank you!
