### ISSUE TITLE
Signup not verifying email with Redis config

### ISSUE THREAD

**Issue by peter-wd-1** [authorizerdev/authorizer#200]
**Version:** 0.26.0

**Describe the bug**

Signup not verifying user email with redis.

**Steps To Reproduce**

use docker image for redis:
```
 redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7000
    ports:
      - 7000:7000
    networks:
      - api-service
```
setup env for authorizer server:

```
    environment:
      - REDIS_URL=redis://redis:7000
```

signup:
```
await authorizer.signup({
      email,
      password: genPW,
      confirm_password: genPW,
      redirect_uri: config.authorizer.redirectURL,
      roles: [`${role}`],
    })
```
this result out:
```
access_token: null,
    expires_in: null,
    refresh_token: null,
    id_token: null,
```
It all works with the same code if I don't use redis.
Thanks :)
