### ISSUE TITLE
Caddyfile

### ISSUE THREAD

**Issue by VladimirCores** [authorizerdev/authorizer#325]
**Feature Description**
It would be great to have Caddyfile and caddy service in docker-compose which exposes authorized service to https.

**Comment by VladimirCores** [comment]
Strange but this settings does not work:
```
localhost:443 {
	handle /auth/* {
		reverse_proxy authorizer:4444
	}
	handle / {
		respond "root empty"
	}
}
localhost:80 {
	respond "HTTP is not available use HTTPS"
}
```

**Comment by VladimirCores** [comment]
docker-compose.yaml
```
version: '3.9'
services:
  authorizer:
    container_name: authorizer
    build: .
    ports:
      - "4444:8080"
    env_file:
      - .env
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy:/etc/caddy
    links:
      - "authorizer"
```
