### ISSUE TITLE
Mysql8 doesn't support UUID 

### ISSUE THREAD

**Issue by agarwal-nitesh** [authorizerdev/authorizer#77]
**Version:** 0.4

**Describe the bug**

Automigrate and SQL query fails for mysql8 due to UUID. 

**Steps To Reproduce**

On starting the server while using a MySQL version 8 database.

**Expected behaviour**

`char(36)` may be used instead of the `UUID` type. A snowflake id like key might be preferable.

**Comment by lakhansamani** [comment]
@agarwal-nitesh  thank you for reporting this. Will try to resolve this asap.

**Comment by lakhansamani** [comment]
@agarwal-nitesh thank you for testing it and reporting it. 
I have tested and fixed it here: https://github.com/authorizerdev/authorizer/releases/tag/0.5.0

Have used following docker-compose to test

```
version: '3.3'
services:
  db:
    image: amd64/mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:

```
